version: "3.7"

services:
  facebook-account-spends:
    container_name: facebook_account_spends
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: on-failure
    volumes:
      - ./config.yml:/srv/config.yml
